version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: brief
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: ..
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    env_file: ../../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build: ..
    command: celery -A app.jobs.celery_app worker -B --loglevel=info
    env_file: ../../.env
    depends_on:
      - db
      - redis
volumes:
  db_data:
